#!/bin/bash -e

/usr/bin/puppet apply /etc/puppet/manifests/site.pp

if [ $? -eq 0 ] 
	then 
		/usr/bin/logger -i "Puppet has run succ" -t "puppet-run"
		exit 0
	else
		/usr/bin/logger -i "Pupper has ran into an error, pleaserun puppet manually" -t "puppet-run"
		exit 1
fi
